{% set version = "1.0.0" %}
{% set sha256 = "76e5c219bf2266efcf1a84ca07642403463a73eb6d8435efb09a56fe7c761e83" %}  # Replace with actual SHA256

package:
  name: addeam
  version: {{ version|replace("-", ".")  }}

source:
  url: https://github.com/yourusername/AdDeam/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: bash conda_build.sh
  skip: True  # [win]  # Skip Windows (modify if needed)

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make
  run:
    - python >=3.7
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - scipy
    - opencv
    - pypdf2
    - cython
    - bottleneck

test:
  commands:
    - bam2prof --help  # Ensure compiled binary works
    - bam2prof.py --help  # Ensure Python script calls the binary correctly
    - cluster.py --help  # Ensure Python CLI tool is installed

about:
  home: "https://github.com/LouisPwr/AdDeam"
  license: GPLv3
  summary: "A Fast and Scalable Tool for Estimating and Clustering Reference-Level Damage Profiles."

extra:
  identifiers:
    - biotools:addeam
  recipe-maintainers:
    - gabriel-renaud
    - louis-kraft
